In [1]:
import pandas as pd
from gop import *

In [2]:
print(pd.__version__)

1.1.3


In [3]:
df_trans = pd.read_pickle('trans.pickle')
df_trans

array(['trans_manual', 'trans_zero', 'trans_reff_complete', 'labels',
       'trans_auto'], dtype=object)

In [4]:
df_phones_pure = pd.read_pickle('phones_pure_libri.pickle')
df_phones_pure = df_phones_pure.reset_index()
df_phones_pure

phone phone_name transition_state hmm_state   pdf phone_pure  \
0        15      AA0_B              263         0     2          3   
1        15      AA0_B              264         0   225          3   
2        15      AA0_B              265         0   225          3   
3        15      AA0_B              266         0   225          3   
4        15      AA0_B              267         0   225          3   
...     ...        ...              ...       ...   ...        ...   
21990   342        Z_S            21933         0  5996         40   
21991   342        Z_S            21934         0  5996         40   
21992   342        Z_S            21935         0  5996         40   
21993   342        Z_S            21936         0  5996         40   
21994   342        Z_S            21937         0  5996         40   

      phone_pure_name  
0                  AA  
1                  AA  
2                  AA  
3                  AA  
4                  AA  
...               ...  
21990               Z  
21991               Z  
21992               Z  
21993               Z  
21994               Z  

[21995 rows x 7 columns]

In [5]:
df_target = pd.read_pickle('target_epa.pickle')
df_target

array(['phones', 'phones_names', 'align_transitions', 'target',
       'target_base'], dtype=object)

In [6]:
df_labels = pd.read_pickle('labels_epa.pickle')
df_labels

UnpicklingError: invalid load key, '\x00'.

In [8]:
matrix_gop_robust(df_phones_pure, 6024,1)

[[array([1., 0., 0., ..., 0., 0., 0.]),
  array([0., 1., 0., ..., 0., 0., 0.]),
  array([0., 0., 1., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),


In [19]:
loglikes = pd.read_pickle('loglikes.pickle')
loglikes = np.array(loglikes)
alignments = pd.read_pickle('alignments.pickle')
alignments = alignments['spkr109_10']
df_scores = pd.DataFrame({'logid': ['spkr109_10'], 
                          'p': [loglikes], 
                          'transitions': [alignments['transitions']],
                          'phones': [alignments['phones']]})
phones = df_scores['phones']
transitions = df_scores['transitions']
print(phones[0])
print(transitions[0])
df_scores


['SIL', 'AY1_S', 'TH_B', 'IH1_I', 'NG_I', 'K_E', 'SIL', 'DH_B', 'AH0_E', 'SH_B', 'IH1_I', 'P_E', 'SIL', 'W_B', 'IH1_I', 'L_E', 'SIL', 'S_B', 'IH1_I', 'NG_I', 'K_E', 'SIL']
[[2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [11802, 11801, 11801, 11801, 11801, 11801, 11801, 11801, 11801, 11801, 11801, 11801], [38146, 38145, 38145, 38145, 38145, 38145, 38145, 38145, 38145, 38145, 38145, 38145, 38145, 38145], [24460, 24459, 24459, 24459, 24459, 24459, 24459], [31744, 31743, 31743, 31743, 31743, 31743], [28262, 28261, 28261, 28261, 28261, 28261, 28261, 28261, 28261, 28261, 28261], [2, 1, 1, 1, 1, 1, 1, 1, 1, 1], [14148, 14147, 14147, 14147, 14147], [5944, 5943, 5943, 5943, 5943], [36646, 36645, 36645, 36645, 36645, 36645, 36645, 36645, 36645, 36645, 36645, 36645, 36645], [

logid                                                  p  \
0  spkr109_10  [[-0.24202293, -0.46676305, -0.34699762, -0.63...   

                                         transitions  \
0  [[2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...   

                                              phones  
0  [SIL, AY1_S, TH_B, IH1_I, NG_I, K_E, SIL, DH_B...

In [10]:
gop_robust_with_matrix(df_scores, df_phones_pure, 6024, 1, [], [])

1
['SIL', 'AY1_S', 'TH_B', 'IH1_I', 'NG_I', 'K_E', 'SIL', 'DH_B', 'AH0_E', 'SH_B', 'IH1_I', 'P_E', 'SIL', 'W_B', 'IH1_I', 'L_E', 'SIL', 'S_B', 'IH1_I', 'NG_I', 'K_E', 'SIL']
['SIL', 'AY1_S', 'TH_B', 'IH1_I', 'NG_I', 'K_E', 'SIL', 'DH_B', 'AH0_E', 'SH_B', 'IH1_I', 'P_E', 'SIL', 'W_B', 'IH1_I', 'L_E', 'SIL', 'S_B', 'IH1_I', 'NG_I', 'K_E', 'SIL']


/home/marcelo/epa-gop-pykaldi/gop/gop.py:60: RuntimeWarning: invalid value encountered in log
  lpp = (sum(np.log(scores_phone_pure[j][ti:tf+1])))/(tf-ti+1)


IndexError: list index out of range